# Generated by Django 5.0.6 on 2024-09-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
